server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
  datasource:
    url: jdbc:mysql://rm-2zedatbdu60w6m1e20o.mysql.rds.aliyuncs.com:3306/springboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    password: Ngl5301658
    username: ninggelin
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      app-name: springboot
      address:
      ip:
      port: 9092
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl